CREATE TABLE IF NOT EXISTS PLTMULTITENANCY (
	DSENVIRONMENT VARCHAR2(15 BYTE) NOT NULL, 
	IDCLIENTE NUMBER(9,0) NOT NULL 
);

CREATE TABLE IF NOT EXISTS PLTCLIENTE (
	DSNOMEFANTASIA VARCHAR2(50 BYTE) NOT NULL, 
	IDCLIENTE NUMBER(9,0) NOT NULL 
);

CREATE TABLE IF NOT EXISTS CRCESTATISTICA (
	IDESTATISTICA NUMBER(17,0) NOT NULL, 
	FLTIPOESTATISTICA CHAR(1 BYTE), 
	IDPROCESSAMENTO NUMBER(9,0), 
	IDCLIENTE NUMBER(9,0), 
	IDADQUIRENTE NUMBER(4,0), 
	IDPRODUTO NUMBER(4,0), 
	IDBANDEIRA NUMBER(4,0), 
	DTOCORRENCIA DATE, 
	NRQUANTIDADE NUMBER(11,0), 
	TXDESCONTO NUMBER(20,5), 
	VLBRUTO NUMBER(15,2), 
	VLCOMISSAO NUMBER(15,2), 
	VLLIQUIDO NUMBER(15,2), 
	MEDIAPARCELAS NUMBER(11,0), 
	IDESTABELECIMENTO NUMBER(9,0), 
	IDMOTIVOAJUSTE NUMBER(17,0), 
	IDTERMINAL NUMBER(17,0), 
	DSBANCO VARCHAR2(30 BYTE),
	NRCONTA VARCHAR2(20 BYTE),
	NRAGENCIA NUMBER(5,0), 
	CDBANCO NUMBER(17,0)
);

CREATE TABLE IF NOT EXISTS CRCADQUIRENTE (
	IDADQUIRENTE NUMBER(4,0) NOT NULL, 
	NMADQUIRENTE VARCHAR2(30 BYTE) NOT NULL, 
	FLPERMITECANCELAR CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	NRTAMANHOFILAPROC NUMBER(3,0) DEFAULT 10 NOT NULL, 
	DSDIRETORIOPROC VARCHAR2(100 BYTE), 
	FLAPURASALDOABERTO CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	URLIMAGEM VARCHAR2(4000 BYTE), 
	COR VARCHAR2(20 BYTE), 
	QTARQUIVOS NUMBER(5,0) DEFAULT NULL, 
	FLFREQDEFINIDAENVIOARQ NUMBER(1,0) DEFAULT 1
);